"""add veg

Revision ID: 0c15264a8e1a
Revises: 4aa15c893f2c
Create Date: 2021-08-07 15:08:09.005863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c15264a8e1a'
down_revision = '4aa15c893f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veg', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('veg')

    # ### end Alembic commands ###
